version: '3.8'

services:

  localstack:
    environment:
      SERVICES: sqs,sns,es,s3
      OPENSEARCH_ENDPOINT_STRATEGY: "path"
    volumes:
      - ./localstack/3-setup-elastic.sh:/docker-entrypoint-initaws.d/3-setup-elastic.sh
      - ./localstack/4-setup_index.sh:/docker-entrypoint-initaws.d/4-setup_index.sh
