name: 'Test'
on:
  workflow_call:
    inputs:
      components:
        required: true
        type: string
      elastic:
        required: false
        type: string

jobs:
  test:
    name: 'Unit and Integration Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Use Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start infrastructure
        run: ./ci/infrastructure.sh
        env:
          COMPOSE_SERVICES: ${{ inputs.components }}
          INCLUDE_ELASTIC: ${{ inputs.elastic || 'false'}}
        shell: bash

      - name: Run tests
        run: ./gradlew clean build --no-daemon
